import Head from "next/head";
import Link from "next/link";
import { useAuth, useClerk, useUser } from "@clerk/nextjs";

export default function Home() {
  const { signOut } = useClerk();
  const { user } = useUser();
  const { userId, actor } = useAuth();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Link href="/quote">Go to quote page..</Link>
        <div className="flex flex-row gap-x-4">
          {user ? (
            <button
              className="border bg-red-500 py-2 px-8 text-base font-medium text-white hover:border-main-blue hover:bg-gray-50 hover:text-black"
              onClick={() => signOut()}
            >
              Sign out {user?.username}
            </button>
          ) : (
            <Link
              className="border bg-blue-500 py-2 px-8 text-base font-medium text-white hover:border-main-blue hover:bg-gray-50 hover:text-black"
              href={"/sign-in"}
            >
              Sign In
            </Link>
          )}
        </div>
      </main>
    </>
  );
}
